[versions]
# application ----
id = "com.foke.together"
app-version-code = "1"
app-version-name = "1.0.0"

# sdk ------------
sdk-compile = "android-35"
sdk-min = "31"
sdk-target = "35"

# gradle ---------
agp = "8.5.2"

# kotlin ---------
kotlin = "1.9.20"
coreKtx = "1.13.1"

# kapt -----------
kotlin-kapt = "1.9.20"

# android --------
appcompat = "1.7.0"
composeCompiler = "1.5.5"
lifecycle-runtime-ktx = "2.8.6"
activity-compose = "1.9.2"
compose-bom = "2024.09.02"
material = "1.12.0"
navigation-compose = "2.8.1"

# hilt -----------
hilt = "2.49"
androidx-hilt-compiler = "1.2.0"
androidx-hilt-navigation-compose = "1.2.0"
androidx-hilt-work = "1.2.0"

# room -----------
room = "2.6.1"

# work manager ---
work-runtime-ktx = "2.9.1"

# retrofit -------
okhttp = "4.10.0"
retrofit = "2.9.0"
gson = "2.10.1"

# serialization --
serialization-json = "1.5.1"
serialization-converter = "1.0.0"

# proto datastore
datastore = "1.1.1"
protobuf = "3.23.2"
protobuf-plugin = "0.9.4"
protoc = "com.google.protobuf:protoc:4.28.2"

# compose extended UI
constraint-layout-compose = "1.0.1"
android-mjpeg-view = "1.1.3"
material-icons-extended = "1.7.2"
ui-graphics-android = "1.7.3"

# test -----------
junit = "4.13.2"
junit-version = "1.2.1"
espresso-core = "3.6.1"
coilCompose = "2.7.0"



[libraries]
# core -----------
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

# android --------
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation-compose" }

# hilt -----------
hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
androidx-hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "androidx-hilt-compiler" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidx-hilt-navigation-compose" }
androidx-hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "androidx-hilt-work" }

# work manager ---
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work-runtime-ktx" }

# room -----------
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

# retrofit -------
ok-http-base = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
retrofit_base = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
retrofit_gson = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
google_gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

# serialization --
serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization-json" }
serialization_converter = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version.ref = "serialization-converter" }

# proto datastore
datastore = { group = "androidx.datastore", name = "datastore", version.ref = "datastore" }
datastore_preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
datastore_preferences_core = { group = "androidx.datastore", name = "datastore-preferences-core", version.ref = "datastore" }
protobuf_javalite = { group = "com.google.protobuf", name = "protobuf-javalite", version.ref = "protobuf" }

# compose UI
androidx-constraintlayout-compose = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "constraint-layout-compose" }
androidx-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "material-icons-extended" }
android-mjpeg-view = { group = "com.perthcpe23.dev", name = "android-mjpeg-view", version.ref = "android-mjpeg-view" }
androidx-ui-graphics-android = { group = "androidx.compose.ui", name = "ui-graphics-android", version.ref = "ui-graphics-android" }

# test -----------
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit-version" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coilCompose" }



[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin-kapt"}

# hilt -----------
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt"}

# proto datastore
protobuf = { id = "com.google.protobuf", version.ref = "protobuf-plugin" }